#!/usr/bin/env python2
import os
import sys
import json

info_filename = sys.argv[1]

info = json.load(open(info_filename))

if len(info['gpu']) == 0:
    print("Error: No connected NVIDIA cards detected. Stopping installation.")
    exit(1)

print("Detected the following NVIDIA cards:")
for gpu in info['gpu']:
    print('\t{}\tPCI Width {}'.format(gpu['name'], gpu['pci_width']))
print('\n')

yes = raw_input("Do you agree to all NVIDIA terms and conditions and wish to continue? (y/n)")
if yes.lower().startswith('y'):
    exit(0)

print("Stopping installation")
exit(1)
